# Baudrate for RS485.
# Maximum baudrate = 115200.
MODBUS_RTU_BAUDRATE = 9600

# MODBUS RTU Slave ID/Address.
# Valid Range = 1 to 247.
MODBUS_RTU_SLAVE_ADDRESS = 1

mqtt_server = "192.168.123.200"
mqtt_username = "client"
mqtt_password = "123456"
topic_base = "dmxcore100"

# Ethernet static config (custom keys - names are up to you)
ETH_IP      = "192.168.123.202"
ETH_SUBNET  = "255.255.255.0"
ETH_GATEWAY = "192.168.123.1"
ETH_DNS     = "8.8.8.8"
